// Angular/src/app/todo-item/todo-item.component.ts
import { Component, input, Input, output } from '@angular/core';
import { Todo } from "../models/todo.model"

@Component({
  selector: 'app-todo-item',
  imports: [],
  templateUrl: './todo-item.component.html',
  styleUrl: './todo-item.component.css'
})
export class TodoItemComponent {
  todo = input.required<Todo>();
  doneItem = output<number>()

  itemDone() {
    this.doneItem.emit(this.todo().id)
  }
}

<li class="flex items-center justify-between bg-white p-3 rounded shadow mb-2">
    <span class="text-gray-800">{{ todo().todo }}</span>
    <button
      (click)="itemDone()"
      class="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded"
    >
      X
    </button>
  </li>

// vue/src/components/TodoItem.vue
<template>
    <li class="flex items-center justify-between border-b py-2">
      <span>{{ todo.todo }}</span>
      <button @click="itemDone" class="bg-red-500 text-white px-2 py-1 rounded">
        X
      </button>
    </li>
  </template>
  
  <script>
  export default {
    name: 'TodoItem',
    props: {
      todo: Object
    },
    methods: {
      itemDone() {
        this.$emit('doneItem', this.todo.id);
      }
    }
  };
  </script>
