// vuetodo/src/components/NewTodoForm.vue
<template>
    <form @submit.prevent="formSubmit" class="mb-4">
      <div class="mb-2 font-semibold">Ny uppgift:</div>
      <input
        v-model="newTodoInput"
        type="text"
        class="border p-2 mr-2"
        placeholder="Skriv en uppgift"
      />
      <button type="submit" class="bg-green-500 text-white px-3 py-1 rounded">
        Spara
      </button>
    </form>
  </template>
  
  <script>
  import { todosService } from '../services/todosService';
  
  export default {
    name: 'NewTodoForm',
    data() {
      return {
        newTodoInput: ''
      };
    },
    methods: {
      formSubmit() {
        if (this.newTodoInput.trim()) {
          todosService.addTodo(this.newTodoInput.trim());
          this.newTodoInput = '';
          this.$emit('todo-added');
        }
      }
    }
  };
  </script>

// svelte/src/lib/components/NewTodoForm.svelte
<script>
    import { addTodo } from '../stores/todos';
    let newTodo = '';
  </script>
  
  <form
    on:submit|preventDefault={() => {
      if (newTodo.trim()) {
        addTodo(newTodo.trim());
        newTodo = '';
      }
    }}
    class="mb-6"
  >
    <label for="new-todo" class="block mb-2 font-semibold">Ny uppgift:</label>
    <input
      id="new-todo"
      bind:value={newTodo}
      type="text"
      class="border px-2 py-1 mr-2"
    />
    <button type="submit" class="bg-green-500 text-white px-4 py-1 rounded">
      Spara
    </button>
  </form>
