// vuetodo/src/components/DailyTodo.vue
<template>
  <div class="bg-yellow-100 p-4 rounded mb-4">
    <p v-if="todo">{{ todo.todo }}</p>
    <p v-else>Inga fler uppgifter!</p>
    <button @click="showNewRandomTodo" class="mt-2 bg-blue-500 text-white px-3 py-1 rounded">
      Visa ny
    </button>
  </div>
</template>

<script>
import { todosService } from '../services/todosService';
import { ref, onMounted } from 'vue';

export default {
  name: 'DailyTodo',
  setup() {
    const todo = ref(null);

    const loadRandomTodo = async () => {
      todo.value = await todosService.getRandomTodo();
    };

    const showNewRandomTodo = async () => {
      await loadRandomTodo();
    };

    onMounted(loadRandomTodo);

    return {
      todo,
      showNewRandomTodo
    };
  }
};
</script>

// angular/src/app/daily-todo/daily-todo.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { TodosService } from '../todos.services';
import { Todo } from '../models/todo.model';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-daily-todo',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './daily-todo.component.html',
  styleUrl: './daily-todo.component.css'
})
export class DailyTodoComponent implements OnInit {
  todo = signal<Todo | null>(null);
  todosService = inject(TodosService);

  ngOnInit(): void {
    this.loadRandomActiveTodo();
  }

  loadRandomActiveTodo(): void {
    const todos = this.todosService.todos().filter(t => !t.done);

    if (todos.length > 0) {
      const randomIndex = Math.floor(Math.random() * todos.length);
      this.todo.set(todos[randomIndex]);
    } else {
      this.todo.set(null);
    }
  }

  showNewRandomTodo(): void {
    this.loadRandomActiveTodo();
  }
}

<div class="bg-yellow-100 p-4 rounded mb-4">
  <p *ngIf="todo()">{{ todo()?.todo }}</p>
  <p *ngIf="!todo()">Inga fler uppgifter!</p>
  <button (click)="showNewRandomTodo()" class="mt-2 bg-blue-500 text-white px-3 py-1 rounded">
    Visa ny
  </button>
</div>
